// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: routes/v1/routes.proto

package routespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouteService_Watch_FullMethodName = "/claimward.routes.v1.RouteService/Watch"
)

// RouteServiceClient is the client API for RouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RouteService streams the set of routes (WireGuard AllowedIPs) a client should
// send through the tunnel, and pushes updates whenever the server's route set
// changes — so the gateway can add/remove reachable subnets without the client
// re-enrolling.
//
// The caller authenticates with the same OIDC bearer used for the HTTP API,
// passed in gRPC metadata as "authorization: Bearer <token>".
type RouteServiceClient interface {
	// Watch sends the current RouteUpdate immediately, then streams a new
	// RouteUpdate every time the route set changes, until the client disconnects.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteUpdate], error)
}

type routeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteServiceClient(cc grpc.ClientConnInterface) RouteServiceClient {
	return &routeServiceClient{cc}
}

func (c *routeServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RouteService_ServiceDesc.Streams[0], RouteService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, RouteUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouteService_WatchClient = grpc.ServerStreamingClient[RouteUpdate]

// RouteServiceServer is the server API for RouteService service.
// All implementations must embed UnimplementedRouteServiceServer
// for forward compatibility.
//
// RouteService streams the set of routes (WireGuard AllowedIPs) a client should
// send through the tunnel, and pushes updates whenever the server's route set
// changes — so the gateway can add/remove reachable subnets without the client
// re-enrolling.
//
// The caller authenticates with the same OIDC bearer used for the HTTP API,
// passed in gRPC metadata as "authorization: Bearer <token>".
type RouteServiceServer interface {
	// Watch sends the current RouteUpdate immediately, then streams a new
	// RouteUpdate every time the route set changes, until the client disconnects.
	Watch(*WatchRequest, grpc.ServerStreamingServer[RouteUpdate]) error
	mustEmbedUnimplementedRouteServiceServer()
}

// UnimplementedRouteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteServiceServer struct{}

func (UnimplementedRouteServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[RouteUpdate]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedRouteServiceServer) mustEmbedUnimplementedRouteServiceServer() {}
func (UnimplementedRouteServiceServer) testEmbeddedByValue()                      {}

// UnsafeRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteServiceServer will
// result in compilation errors.
type UnsafeRouteServiceServer interface {
	mustEmbedUnimplementedRouteServiceServer()
}

func RegisterRouteServiceServer(s grpc.ServiceRegistrar, srv RouteServiceServer) {
	// If the following call panics, it indicates UnimplementedRouteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteService_ServiceDesc, srv)
}

func _RouteService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, RouteUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouteService_WatchServer = grpc.ServerStreamingServer[RouteUpdate]

// RouteService_ServiceDesc is the grpc.ServiceDesc for RouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "claimward.routes.v1.RouteService",
	HandlerType: (*RouteServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _RouteService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "routes/v1/routes.proto",
}
