// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: routes/v1/routes.proto

package routespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PublicKey is the device's WireGuard public key (base64), identifying the peer.
	PublicKey     string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_routes_v1_routes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routes_v1_routes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_routes_v1_routes_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type RouteUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AllowedIPs are the destination CIDRs to route through the tunnel.
	AllowedIps []string `protobuf:"bytes,1,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	// DNS servers to use while connected (optional).
	Dns []string `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	// Serial increments on each change, for client-side de-duplication/logging.
	Serial        uint64 `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdate) Reset() {
	*x = RouteUpdate{}
	mi := &file_routes_v1_routes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdate) ProtoMessage() {}

func (x *RouteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_routes_v1_routes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdate.ProtoReflect.Descriptor instead.
func (*RouteUpdate) Descriptor() ([]byte, []int) {
	return file_routes_v1_routes_proto_rawDescGZIP(), []int{1}
}

func (x *RouteUpdate) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *RouteUpdate) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *RouteUpdate) GetSerial() uint64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

var File_routes_v1_routes_proto protoreflect.FileDescriptor

const file_routes_v1_routes_proto_rawDesc = "" +
	"\n" +
	"\x16routes/v1/routes.proto\x12\x13claimward.routes.v1\"-\n" +
	"\fWatchRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"X\n" +
	"\vRouteUpdate\x12\x1f\n" +
	"\vallowed_ips\x18\x01 \x03(\tR\n" +
	"allowedIps\x12\x10\n" +
	"\x03dns\x18\x02 \x03(\tR\x03dns\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\x04R\x06serial2^\n" +
	"\fRouteService\x12N\n" +
	"\x05Watch\x12!.claimward.routes.v1.WatchRequest\x1a .claimward.routes.v1.RouteUpdate0\x01BAZ?github.com/claimward/claimward-vpn-client/pkg/routespb;routespbb\x06proto3"

var (
	file_routes_v1_routes_proto_rawDescOnce sync.Once
	file_routes_v1_routes_proto_rawDescData []byte
)

func file_routes_v1_routes_proto_rawDescGZIP() []byte {
	file_routes_v1_routes_proto_rawDescOnce.Do(func() {
		file_routes_v1_routes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routes_v1_routes_proto_rawDesc), len(file_routes_v1_routes_proto_rawDesc)))
	})
	return file_routes_v1_routes_proto_rawDescData
}

var file_routes_v1_routes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_routes_v1_routes_proto_goTypes = []any{
	(*WatchRequest)(nil), // 0: claimward.routes.v1.WatchRequest
	(*RouteUpdate)(nil),  // 1: claimward.routes.v1.RouteUpdate
}
var file_routes_v1_routes_proto_depIdxs = []int32{
	0, // 0: claimward.routes.v1.RouteService.Watch:input_type -> claimward.routes.v1.WatchRequest
	1, // 1: claimward.routes.v1.RouteService.Watch:output_type -> claimward.routes.v1.RouteUpdate
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_routes_v1_routes_proto_init() }
func file_routes_v1_routes_proto_init() {
	if File_routes_v1_routes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routes_v1_routes_proto_rawDesc), len(file_routes_v1_routes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routes_v1_routes_proto_goTypes,
		DependencyIndexes: file_routes_v1_routes_proto_depIdxs,
		MessageInfos:      file_routes_v1_routes_proto_msgTypes,
	}.Build()
	File_routes_v1_routes_proto = out.File
	file_routes_v1_routes_proto_goTypes = nil
	file_routes_v1_routes_proto_depIdxs = nil
}
